### ISSUE TITLE
r2 frida://launch works only with some apps in iOS

### ISSUE THREAD

**Issue by trufae** [nowsecure/r2frida#232]

**Comment by mrmacete** [comment]
the reason is that r2frida's agent wants to use CoreFoundation while the process is still paused. That fails on jailbreaks like checkra1n (and also on some macOS targets) because frida's early instrumentation process doesn't explicitly initialise `CoreFoundation` AND it can only be initialized on the main thread (so there's no way to do that from a frida script while the main thread is suspended).

A possible solution to this is: https://github.com/frida/frida-core/pull/340 which attempts to initialize `CoreFoundation` during frida's early instrumentation, if the target process depends on it.
