### ISSUE TITLE
need to be installed as user instead of root

### ISSUE THREAD

**Issue by gogo2464** [nowsecure/r2frida#307]
`make install` works but `sudo make install` does not works on debian because it install everything in the root folder.

To solve this issue I am going to fork and to update the readme.

Fell free to assign me.

**Comment by gogo2464** [comment]
I am ready to merge if you like.

**Comment by trufae** [comment]
Uhm your fix is correct because install puts the plugin in the home directory. but i have recently started to use `user-install` and `install` targets to cleanly differentitate on those. r2pm should handle that transparently. i will merge your PR but i do believe we need to support both types of installations
