### ISSUE TITLE
Implement support for frida://tcp/host:port/pid

### ISSUE THREAD

**Issue by trufae** [nowsecure/r2frida#31]

**Comment by trufae** [comment]
Ideally frida://<host:port>/<pid>... i dont think we may find much deviceids with : in the name.. but we can change that later

**Comment by Manouchehri** [comment]
Lazy workaround:

```bash
socat TCP-LISTEN:27042,bind=127.0.0.1,fork,reuseaddr TCP:172.17.0.3:27042
r2 frida://tcp/Gadget
```

**Comment by radare** [comment]
This is done already. the problem is that host can only be an IP, not hostname, for some reason the Frida API doesn't resolves IPs addresses out of hostnames. and its only ipv4, no ipv6

You can do this:

$ ./frida-server-10.6.11-macos-x86_64 -l '0.0.0.0:9999'

and then

$ r2 frida://127.0.0.1:9999/92202

**Comment by trufae** [comment]
Hostname not resolved because its not done in frida land

**Comment by trufae** [comment]
Closing as "fixed" and continuing the work in https://github.com/nowsecure/r2frida/issues/123
